micronaut.application.name=vrummAutomoveis

micronaut.server.port=8080

micronaut.views.thymeleaf.enabled=true

datasources.default.url=jdbc:postgresql://localhost:5432/vrumm_automoveis
datasources.default.username=admin
datasources.default.password=admin
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES

flyway.datasources.default.enabled=true
flyway.datasources.default.locations=classpath:db/migration

micronaut.router.static-resources.swagger.paths=classpath:META-INF/swagger
micronaut.router.static-resources.swagger.mapping=/swagger/**

micronaut.router.static-resources.swagger-ui.paths=classpath:META-INF/swagger/views/swagger-ui
micronaut.router.static-resources.swagger-ui.mapping=/swagger-ui/**