micronaut.application.name=vrummAutomoveis

micronaut.server.port=8080

micronaut.views.thymeleaf.enabled=true

datasources.default.url=jdbc:postgresql://localhost:5432/vrumm_automoveis
datasources.default.username=postgres
datasources.default.password=postgres
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES

flyway.datasources.default.enabled=true
flyway.datasources.default.locations=classpath:db/migration